"""initial schema (API-owned media + processing tables)

Revision ID: 0001_init
Revises:
Create Date: 2026-05-30

Scaffold migration: creates all API-owned tables from the ORM metadata. Once the
schema stabilizes, replace this with autogenerated, hand-reviewed migrations via
`alembic revision --autogenerate`.
"""
from alembic import op

from app.db import Base
import app.models  # noqa: F401 — populate Base.metadata

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
